---
title: "Expert advice from experts"
author:
- familyname: Curie
  othernames: Marie
  address: University of Paris
  qualifications: Nobel Prize, PhD
- familyname: Curie
  othernames: Pierre
  address: University of Paris
  qualifications: Nobel Prize, PhD
email: mcurie.notreal@gmail.com
phone: (03) 9905 2478
department: Department of\newline Econometrics &\newline Business Statistics
organization: Acme Corporation
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  monash::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---




#Section by IPS
Edit created by IPS

```{r}
library(tidyverse)
library(here)
library(dplyr)
```



# Section 1
Anh Kieu edited this.


```{r}
covid <- read_csv(here::here("data/worldwidecases.csv"))
```


# Section 2

```{r}
covidrate_vis <- covid %>%
  mutate(date= as.Date(dateRep, format = "%d/%m/%y"), cases_rates = ((1000*cases/popData2018) + 0.01), dead_rates = ((1000*deaths/popData2018) +0.01)) %>%
  dplyr::filter(date != "2020-12-31") %>%
  group_by(countriesAndTerritories, date) %>%
  summarize_at(vars(cases, deaths), cumsum) %>%
  dplyr::filter(countriesAndTerritories %in%
                  c("Italy", "Germany", "Greece", "Switzerland", "Sweden", "France")) %>%
  ggplot(aes(x = date, y = cases_rates) ) +
  geom_line(color = "#1F9E8E") +
  facet_wrap(~countriesAndTerritories) +
  theme_bw() +
  ggtitle("Covid cases (rates)")

```

Added by Cyrus 3

make changes


